language: node_js
group: bluezone
node_js:
- 6.3.1
sudo: required
before_script:
- npm install -g gulp --progress false --depth 0
- npm install -g istanbul --progress false --depth 0
before_install:
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo apt-get update -q
- sudo apt-get install g++-4.8 -y
- npm install -g npm@3.10.4 --progress false --depth 0
install:
- npm install
script:
- gulp test
- gulp build
deploy:
  skip_cleanup: true
  provider: script
  script: "./bin/deploy.sh"
  on:
    branch: master
    node: 6.3.1
env:
  global:
    # Common Unsecure Variables ( Same in prod / stage )
    - CF_ID=pkadiya@us.ibm.com
    - CF_ORG=MarketplaceOnboarding
    - CF_ENV_PREFIX=CFCI_
    - CFCI_TEST=TRUE
    - MEMORY_SIZE=512M
    - CFCI_SEC_PATH=home/
    - APP_PATH=./dist
    - APP_MANIFEST_PATH=./dist
    - PROJ_PATH=./
    - CXX=g++-4.8
    - CFCI_SOFTLAYER_AUTH_URL=https://dal05.objectstorage.softlayer.net/auth/v1.0/
    - CFCI_CLOUDANT_USERNAME=opwb
    # Common Secure Variables ( Same in prod / stage )
    # CF_PWD
    #- secure: pwj19kzNTr6hZUyblF/AbkH8AsAivdF9YT3Z0gGpPS8CiWR1EIROwU/PQyn7fWlctc/+EOxI10pIF0l+ytBU5cGb8LtJqkMgyHgCTOUtxKkyzD0s3gGLIVlCX11EqbaaiXeZpGmQFS9N07GcsHqSFeD40Dq6RGcK6h7AZUTowT9NPnUi6Tghw0MmIFK0s+/FFBR72Kg/ugj1KD6npx2cLiaGjwd91m52HCz9Zsa8U9StsOj9s4F3NbLkqmdZTKa+FIol6lmCiHF2nKClWM0WZO3GSPQWvrcm1p+EYLkiy1/cz4d2xv90tPzUPcUz3OBS+XpV07t2JS0vWybS9ZeCLHFCBYzUlBJDjNRWL99BoxXfQ78uXhyuwOckhOPhVmL9ryOY4ZJcbfvXh+O4v0hYpnmNhby98bF5dUhZpevg9ZnaAe93w6HGwTXC4ojsee1a+OaiNvjwOEUy3Y59nQjVP0yKX7KgRLsmK0oSYOVA6D2diXRb0eqk3pGPl7xuvQm8OK/T5exbVRCFjb1ULBE++UQLtCHqiLJ4zrMBZ9AG6QPG2Yq7a8GCKP7RdOU/KUtM7+4nSI0vwdOUEChxAQupP2hvMIntBXOhogbfSu/QtO/yiqGg3MPClj9Lkk2BKMtlh2664EUs36pZbtRgdnzylGXDpVg35E9XwoTTWdQ2Y9U=
    # CFCI_REDIS_PASSWORD
    - secure: u5839G2w+4I/zBqtixesvhQ5QPjx/FqA28pi6niANVgdEdP25/gwHI2tyL6v/uM1Tltm3Q/FucPqeSsBXrfMGuBjpE9B34YhmUNfdRF3dzmUdFl4n2lCJgVua3L52V3bkDdEUMmffXI0w91QNhmiSTDSVPAHRx6zhW4+uVfHCPtW1LTT/geXjxu1gjQcusg5xX3WVkdom3uPgb8bLdaloEM2Sf0OwgVA6FUmFE6g9TPFSsqS1svS0LZse+XyqRaVLdejNrTv/K9EFAPpGxDHlqkNdvEbOqOSMC7H2CNel43gNS3TbakkjXa67VXESpOD5PiL1RuFFoZZ35bE2hOw9plRMMm7hZwm9Ywykv6NNknB+/+UwImeGpB4J7e210FReaq7pPI9fp+YCoFxTCBaUm5TxnunldM4/cjJ6BcMwCR7LJR2etdtDG0zN7dniRbTRZegO6Fple4b2sio48W0eGY9fY+BD0h1ld6Vj1jAwcAF2k+/Z4WSd6fMl/dkjGltQ2y2ZN7dD2+4Fl7xN7+NjZivhKABPJmsUB8eWn157FXDTdFEFq68Z497SLO3oGkMY1vPbjZqGiHW3PMeTLv7WfBgUAtYS4RU0zxkD/5AZ1RcNlCSX9vajr1P/NMRVHmJIuR+kttEJPrg/dRUvUtVBn3E+TRVVqUy4pwYAehDhI4=
    # CFCI_CLOUDANT_PASSWORD
    #- secure: vN5afdycjISTGlKsjup0fFRpHDQ4fZvfsQyBfjSCXlZwBMMW+oYNksoICa0nB/pcNToSS0K342DjDc2AmBW+uIljSGq7Qz2l1cqgxgyxKGNQlzsjz423kaRwN8639CgrCFYgyBOz8UVJxXEj5tCxmTt1rjWVZ4LzjM9c8DxcxVOXxhBmdmBrH66nyEouWQWnbb9Db5Q54uLpcOJoorg8LsntWn3reDkbHZ4qgpmlI5eQNfvb15qYU7A1IDJXVDKuA8fkfeW5Hn8627SMYG54nuMh5R/Bo4QgyIi7rcEcxj6Otas4vgF6j01Rv5ZRmexNRLp1x0ZuWnutpxkT2bxp1rxFEakTFMP+QMVYBLl1A+adVO38kfdgSgM/cv0uG65BwxDaH/UktIXio1fcMIOsVo+BJmURIUeC7lROKhPm+SrfYrhMwrDYRVRFKRbwOc595DjkiqHNZsxNPBXiJK6goU5hD/v2aGnpIDKBZKpKMes3qYSzzufO5a+9qTE2FqDAqaTrgb69t+fmqqgYewR6d4JwrQfbofsdhaP//UPbfWZkvpuCGQgoRk4/TbSWNackxq+of0D+9404bomeBdG3lHUFPvllN6bSn7ir0rhveKCyotE7CMvMLF0rB9JxiDPdoBxiOro9staLdITTUV/rINSXc+1ZuQfMdwaxTf+SNzY=
    # Production Unsecure Vars
    ##
    - APP_NAME=opwb
    - CF_SPACE=prod
    - APP_MANIFEST_PATH=manifest-prod.yml
    - NUMBER_INSTANCES=1
    - CFCI_WEB_ROOT=/marketplace/operator/
    - CF_NODE_ENV=production
    - CFCI_SOFTLAYER_CDN_URL=http://29DB6.http.dal05.cdn.softlayer.net
    - CFCI_IDAAS_CALLBACK=https://opwb.w3ibm.mybluemix.net/marketplace/operator/auth/sso/oidc/return
    # Production Secure Vars
    ##
    # CFCI_SESS_SECRET
    #- secure: YsbLQ6nCDP31n4Ubmkn4wA63gMu9MUOkmO+EWT7lUQT/OASoouF8EgLTmpaafcPkb2hPUbqTzy+D1Q3dSfTPow/WHHSGbvsCMg61RqP+gDKW9+KANfX3v6koPNSVmhA6c37mVt1vvZwkfYTVBazyw2PF2Wvi5kxOudDpdFx3s2OZ6enqgG+h8byaZLQz7BNaM/pK9amWFEfsZx9skkIQWrn35ezT2R2sDaWlwxrdyFCIt74r73paso8y3JOuNLl7Hgp2VQJs2hbfiDCRyaGJMRGh1OD8bcXt3zdKY10K+47ur7LdByr32vti9gdzmZuHwBY00EP10MlJN0ds0UpxzEA8/fIp+/ioNNSaet8DYQncCXqX7DWahP0Bm40zu1CauvUkAYUkVqazqamSmWLvaVljK2hvxKVq6xrvyUyYiXLDqEGtMJbmJv6ZdNPnkPaq9IHxOwgA+wZ20qS3rSO/J5owW0tW1ipysbrH8SSSNfBlX1Vu4rkbOxjMSehjJ+KZdQQz+ZNypPjzu8qUfkHQnfSOkrPbp4w7+EwGjdcoL14rV00wksjW/QVJB/qxA0EGmZEeitA8W8p2C9SQqLapSeW12AwW/N31oiToHk8V3hl6hMFFlZ5HYr86aC0AyqvlEMVXf8IsONX61g8YPUeiV47vr1xLhvb8UyT3JvQ9RS8=
    # CFCI_IDAAS_CLIENT
    #- secure: gZmXUEaTSjHOd3cQxOQZtPAQwoJVEPS/8HBk5o2C6cZq+JqVU0h4gqtFmR3yGrB5AfHBfsXtTE4H7x3KDPUYrUIwymDbf/I2/SX/EqR4g77zFYmQnapR58JM/HIbRn8GuNQegoYVUG9WRsrmqBUoDd5LcPtTnHlJqO8Bp5obAuFC+F9rxdRCzlio9lIll4eXygt2bUtkvYNFGEyqWm+WRSrjhm3/K1ts5iJLfwG4Z+0TQGG/aqVhN2bKZzzo7VuGcGvx/DWElAkuNGbrlBaQmSOvcRBQVXhWZk8vMIvfuk1JfqezEVZtdTVJaDnDpHwgCXzaEKfI+4QSY/06jPvx22gIheHOMFbbv9/XysJhV9YZBCxfcS66aYeHk4gXOzWkcXpeUwKIH+Z3wVIbPTDiTHIqg/+AQ9CdNdTu/OFN7NLOfeoAkrOEfRQnYEtDKINyhJ71jampmC/M8JkWG4V8mEMnX7AMmjV0JORgaKDwcA1nsgvOWb+tTc1MyNEFROx0zNHdW48uSB3M+bCkELaQTwvg06M55KdIpBik1z5hgdpjKXE68ocliDPKu9XMq8Hr+cP4kqoE2BROva0xhaIQBTvtc/wUd9V9Fi/PG1jd+dd+dmPdZt45ylxAMlADOIYWNriG8tAEJUYyFCMg9czCGonv0vhlfjJIRE2llg0wvts=
    # CFCI_IDAAS_SECRET
    #- secure: WJ7dODFAFPAD4IuvY9jtgh3mxz9TjgeWgKNGW+yNNduZogv/xxy9EGrq6kfn8ms1hB4qYe6G0Ya9WjeZzHlD57OHbplNKKjOlfwhP/aX06MeTpQaa+rNvQ3jco7p6dEahFh/7brWPiaoff3uVDyLFkBPOygO3RKJs4BCru81vyrUIUleiTW49S4Ll0FIXgtb4MqT1cj9bhtiGFQHMSwpqVuwbtFZLXew/2QG80i/EHZtt3knivW+C1WSCn6Z+GZdJjWtF/RxPWvQylZX2bSm8gqqgfzWFNX63JSYx90fqXS7uMCaLFotebykMvvtb6v9UEdtMry+aPa2lsbf1G+LCYIzjDcaz9oBMzbeTkl/C3qNPR0TbtTk4R5Eg5YFu/3ERB41KKv2Mlz+DPbKeZqlv+617FMlp9PpW+R9ZvxMdNa4LYkzhjs1a7rfVF5P2oOto6PFGDnIXx9DiAWkot1JFbDojMh7j4Qdi7aA0CuYZBiEWST0DRgQdJFkKYoA1cYlIjXRHrLV29275kWCzb8x8uJecbVIO/ouDvwAPOycsFEDovUyEJM7i8YzzuetxrjdUbEauHl7JupdVnrrmXlP5346wQiyPMKaAFxwnGkLm/oN4suGXjvkRC7M85Y1UxdeqblLMU7iTdcGXXgmqxZldupkIoxsUdR/H12XAyiCEn8=

    # Staging Unsecure Vars
    ##
    - STAGE_APP_NAME=opwb-stage
    - STAGE_CF_SPACE=dev
    - STAGE_APP_MANIFEST_PATH=manifest-staging.yml
    - STAGE_NUMBER_INSTANCES=1
    - STAGE_CFCI_WEB_ROOT=/marketplace/operator/
    - STAGE_CF_NODE_ENV=staging
    - STAGE_CFCI_SOFTLAYER_CDN_URL=http://223ae.http.dal05.cdn.softlayer.net
    - STAGE_CFCI_IDAAS_CALLBACK=https://opwb-stage.w3ibm.mybluemix.net/marketplace/operator/auth/sso/oidc/return
    # Staging Secure Vars
    ##
    # STAGE_CFCI_SESS_SECRET
    #- secure: tZRWQhWC/DGeV+KaocBGy68FJkamqsm/NPyYY5NH8h7VtxLi2bnqgXHlzxCyVJsdiUreIx/sAg9yknTMrSAR39KR4XECHnTAzVaA8BdHTTITFMt11wz3lvm7+xiudWuemDrFnARcIxNGRwBpCczs1Hr0U1GvsDNDIwWwvDADB0u/5Gv+k2BGWcVKk4AsQ/5AGtowloLIsiSLHP3iXp2WwuOBNGGj2MwrjEB2zKUy89dO7clTlaL7ehG/t++f/5+IDApsCc8Ph5+qJ/BO0/Ap+few78qH/GAWf4Zaf3jcHBTJK9Q17mGHd7t/7v2hCgoxTsb7C2FdkBLV+cOBJ3/0fvM/ITzilLdCm9kUEgW/oECEp5B7c9ZGvJkrU94lGTadrcRRGsY89ceoKSSCZIn4H5KjPVSv6uXnc7pbfM8L7ZD3U3mzCo8lib/kEDDE5cmUkdF/+inuRxFAdA+mSE7MnH1YW0vjWS1+cJKLJCsJI6nENW66EBwZ5quewDPzOUHiNj7rfXqbNcXat2z+fEDWOeT1MJMyMBzg/tIGuxLzXnCc+S1G5VcHr5Y615BuZTY+ynKpkPmnTkSc9gyrNCAkpfNzp1Z7NnTu8JmVHqxqwLx/cA4zyQKwXEaZobv+9gxA7l5qTwpS6JnshFVVK/Qw2ZjGcTwGIleeHODKdrUGb6A=
    # STAGE_CFCI_IDAAS_CLIENT
    #- secure: CrGKq9/qDQZ++gdje+4nyaDMvbhaagXRO/8aMpXeyy+nv0Bfj2DJTyrNcugP+HPZwPUPnS0PBJlvoYNPWVTaxCEmFzfTTsVXCJunofDHspv3CLFq8WmI+zW91HXx3iIrBZxTjSVFOnb2OeesFxskuw3g9iZ9dq/3RbD61HA4VEwkvCCSulG5JLBLlYkcaeJzVjj/nhYPQaS7uZ6LgSL+e4OLUW5D2F8TKjAdggW1sywZBfcd7ChV5IYosECd8iU+LcyDndgd+ojm4ZJqnGHiZcRMA+JDAEdPOhIKXa/9Cfl1+HMgDCPovf31fIvi/0uPTMlKFCWk1KYL4C/NWLspHTuLyug6AUClEhnc1MlK09kEphKPn0KnuNGoIMH85fGIWzZaSY++hBtb1a6HQfATeKCcxzg5DOPAR7Q7YzbJgAYmqMwWYUn+fcuypgJjnVT+VmoxheZ818vbSbF94NixcN4l8qOsCy9PkmX614NUFKzwENZ2+9FPVby/uAj/RnXa7ahS797fpAEngLjS/hr4ZWDT9eWh6hyINbzTTJ14mcjrXhYNVddTLa8yYtHj2sqZzJv47XehMEHZWhCfTb20/bamB9MtrcZjjhbGyymikfXjhg6oJltQ3Nn3VGkS4c4VPAbnlcFsRWppM7HvXtMF0r/q/Yz7sbzIzKEcvUBhUls=
    # STAGE_CFCI_IDAAS_SECRET
    #- secure: RB7GVjbD7lcZPFtyKZTVlBCOn9HRjpvJ8EFpnQO41zT4NWSDfABlz5RHQk/u1bENXZ4JQwgbWcGbINuA2ir+uqytgoM7qBqTCTdwsKiIs1R2uSaxJIEOR6zllXRHBIJ/UxCTGMSDZSFa3xml57ZiaTG0+NLwvQutZwM7tgyUwwYV1Z0JmM8zbgg4J2tXRefedmX4lb/M5tKmoZMfRi3eGVk3PSpXFQg66FB4aWdKFHkhIbCESNAmxZcHW2FFjrNv9g4lrvn+UaCDhBGPnchJxkcJz+jsaoxAhCDyjkotcIRGVZwCAKFz0ufXIotH3Si5EaFYWekd0YfOPh/ZzhYLYDvB/f6+OAhgOEvjs+Bvx+RTwVE1fptVb3kpTU+cY9InoOed9eRpdyEPrCGYFcxdHFSzKu9N8ZwIMsPsCfudPJviRX1ZkCnDi4E0R+l+BZJvAwdfH5VrKGjpkYK2ke9i4tzeqI+IJMr1cPSBcoq8EyXE9bV4AuLsNXKawJ2WvQosLL513dcGswWDoTY4zRY/bbOEkCFMUMkpJ3SUmnw+DAgsYenfL8SlGyZi59nX0LIW02188hUT/3quTwzCCu+oh5T/16eDbk3aFiAWly63Vfhu69sAzXSiwGwnzDB8ZTJmXi4D2Oj3RhdZjSBQ+TMpkFPpMQwHX88k34N0FL8ObPU=
