language: node_js
group: bluezone
node_js:
- 6.3.1
sudo: required
before_script:
- npm install -g gulp --progress false --depth 0
- npm install -g istanbul --progress false --depth 0
before_install:
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo apt-get update -q
- sudo apt-get install g++-4.8 -y
- npm install -g npm@3.10.4 --progress false --depth 0
install:
- npm install
script:
- gulp test
- gulp build
deploy:
  skip_cleanup: true
  provider: script
  script: "./bin/deploy.sh"
  on:
    branch: master
    node: 6.3.1
env:
  global:
    # Common Unsecure Variables ( Same in prod / stage )
    - CF_ID=pkadiya@us.ibm.com
    - CF_ORG=MarketplaceOnboarding
    - CF_ENV_PREFIX=CFCI_
    - CFCI_TEST=TRUE
    - MEMORY_SIZE=512M
    - CFCI_SEC_PATH=home/
    - APP_PATH=./dist
    - APP_MANIFEST_PATH=./dist
    - PROJ_PATH=./
    - CXX=g++-4.8
    - CFCI_SOFTLAYER_AUTH_URL=https://dal05.objectstorage.softlayer.net/auth/v1.0/
    - CFCI_CLOUDANT_USERNAME=opwb
    # Common Secure Variables ( Same in prod / stage )
    # CF_PWD
    #- secure: pwj19kzNTr6hZUyblF/AbkH8AsAivdF9YT3Z0gGpPS8CiWR1EIROwU/PQyn7fWlctc/+EOxI10pIF0l+ytBU5cGb8LtJqkMgyHgCTOUtxKkyzD0s3gGLIVlCX11EqbaaiXeZpGmQFS9N07GcsHqSFeD40Dq6RGcK6h7AZUTowT9NPnUi6Tghw0MmIFK0s+/FFBR72Kg/ugj1KD6npx2cLiaGjwd91m52HCz9Zsa8U9StsOj9s4F3NbLkqmdZTKa+FIol6lmCiHF2nKClWM0WZO3GSPQWvrcm1p+EYLkiy1/cz4d2xv90tPzUPcUz3OBS+XpV07t2JS0vWybS9ZeCLHFCBYzUlBJDjNRWL99BoxXfQ78uXhyuwOckhOPhVmL9ryOY4ZJcbfvXh+O4v0hYpnmNhby98bF5dUhZpevg9ZnaAe93w6HGwTXC4ojsee1a+OaiNvjwOEUy3Y59nQjVP0yKX7KgRLsmK0oSYOVA6D2diXRb0eqk3pGPl7xuvQm8OK/T5exbVRCFjb1ULBE++UQLtCHqiLJ4zrMBZ9AG6QPG2Yq7a8GCKP7RdOU/KUtM7+4nSI0vwdOUEChxAQupP2hvMIntBXOhogbfSu/QtO/yiqGg3MPClj9Lkk2BKMtlh2664EUs36pZbtRgdnzylGXDpVg35E9XwoTTWdQ2Y9U=
    # CFCI_REDIS_PASSWORD
    - secure: X0PdR3sUfnDN2krBe8J3auXkFpdsbcQ+POdE+gjQKgMz8tDwsOyVFxIwtS39SZ2eTh/u5qWSc1RVixHLN59P+wbS5QkMzTUznEa/f4l/vn1UDq5nozW1qe0WnD8vZqG3g6vG5AKA6rbr4Xh2BjHYUqbvxhCfDgylAMRo0j4U6QIgCw4sO5vn28+ukG8pjj4AnHnyEBisrFjdNdH4wsnrZcad4Sje43JvDe4nCyv24zTwMzAXANQn9dtqESqURM26RweRRb3knoIumzMIBB5aRdFnWNVZSEL/CWrmramjNfHZZEBANlXG0EJ+QoktMeyhFtk33DFhazgaRDS6woEIkh4/BWrxNTgxbrD38eYB5L/lTvQSia9lZT8VKxeQdFeFXSgCtSjtSyW+hul6cTxNLyjaKVCSTSxKEn3JxqD93Yeg6UulNiHVjTBbTUeppo+TJ5d1uxLIYinFhMRHYN5lr/fH6NEMduwGncZu9JFIUyat1db7SAOIsccq2TuXemffj2kBnGhjFbQOR518oFLDosJIQ77vSZHMwxAx8GGSgrLxLX/dJr49sL92OgyOfxOQcmlawL2S3fB8oXsZ1V+jZWOTfFsh9JQySNxEfR8H9hRBdDzDO1U9h1Tk5Rpjzi5SagnYe2syB96hZ3+UjhVQp2dPqpcAZocGr5h0W/2S3N0=
    # CFCI_CLOUDANT_PASSWORD
    - secure: G6DRhexQAdTgpw3mfxtrPBVqqw9l/5scQCf/+usqbKLYKhzoXEMTnztY0xpm/ESA4caQBwcOm5XZnVBzYYeJKnMmNf9MGXb8LvIDQRiB0JvVsm79hIcEgEw9JOiLjlp1ve30QnaCbL+rhr8BvWk1S2fgP5QtpnW4y2zX4XaULfFMjm9s2XJOG7aPr0Z26g2eDd+A1qu/veP4H+HaJXAXxujDCkT+cVpfASrzT30AEFltIICKXQJcM3xcYsIHrbKmOo22TtEVc33dJrq+xN1h/fgGw6HLu4Yxj41069HmWknDth15R47mB2QaPbZf6EPGhw2Iq00I2HYUbO9gpBBE05ZT9M/BXgmRZWQeRFc5zP69rEFIIZS01AhU6KHFB+BYe7tG/Yk8YfrhQeP053U1FT4qO2AjABe7Bgs3PTRv4ofAtOnwf2HVC2Fsyg+sWs+1FiHXuiPCziXoDBT0RU0rS5KLesZZ6iZpzLG1Q7XWIumXbnBI7wYVNnnzVtDGlvmiOkbAKHjIi+99cIZlKx9VV3hD1862Wv7tmtYbPrAk0Jh7n3DC+UMmDM3fiLIVIKYIZpXF+d3ouqNfAMqRR+eIUD2y/liHzEcXLegYj2/cWot02jX72K4ZX0idhTkt62abWoVFlBX3IX8L+JMQ36JouIL/QL5gSNGJkUs4LSXuVFA=
    # Production Unsecure Vars
    ##
    - APP_NAME=opwb
    - CF_SPACE=prod
    - APP_MANIFEST_PATH=manifest-prod.yml
    - NUMBER_INSTANCES=1
    - CFCI_WEB_ROOT=/marketplace/operator/
    - CF_NODE_ENV=production
    - CFCI_SOFTLAYER_CDN_URL=http://29DB6.http.dal05.cdn.softlayer.net
    - CFCI_IDAAS_CALLBACK=https://opwb.w3ibm.mybluemix.net/marketplace/operator/auth/sso/oidc/return
    # Production Secure Vars
    ##
    # CFCI_SESS_SECRET
    - secure: SBru12hrJTzuxL7kGfHlmZs+touSrJuJ8kRO8JKGAAEjfOAcZb5wsLiDiwtLGI+ZAbSy7Rr8AtzqW/YZbbFRdnLOVaWX6M+7P9ncITt65EZV1QVgAhpjQacNKwYJu8zVQuHzFrS/Q/rd+/Zzw7hQHmdFdgL454+2Grtw1bWlkenZQJprxNkoKkfNeLzlph+WBu3rtckh4uBYMXhhtQnWvln2h9/mHwF5k2+z50qVDVwiWu0wfSyw8fXKRsM86hVyOGqzlbSAQY9H+tw0Pf/QOnVvqQ1rz/uRLoLm2qXrB9ckQhjeWMjrJyOHGDCSzXBgYzUiS6RPAFibYiipNDN30D7sxEJDGl+UB9rZxGwx5voTH6DOM3Pc4FctkesgA05DE42VqUKqsiEkcWqeGMvDiW2cJN0iLYtHx3BfnUK/MU8kfGVkSNnH750CSVQ57trYAWUF3JFNvAhoTjHvGlPWTmnxKb+fG/eXl0IpumMz3hvaWSKkpMe5VSgmQgyG7fFaty5n5NiS9mkvMnv+uVslpndNomjgUwzqeyipJ5Sn328SHWi195Twnpk/pcXrPNzD6KJmltqlWh+xMhDNqp7cY3BNjQJIk+YRgFICRIVdxMB4VrBE3go7wfvCHmvgQaLtRMaoijJkv6F9oD7IGG4NKeHbY9PhJt3vzA3vVUHXCrU=
    # CFCI_IDAAS_CLIENT
    - secure: bDa0jmAU6QcyqJCABMC0uF+4PzNu+BJ0znMu02NmbyVQMjv539SVu6WpC90TcUO2EeKtk04XIxg+F2bhc1d2wMNpmHoMUYAyDo8nQfHM8Fowmf4nd7wSDGxG3Mn/Co7//XgdEGxn7utU2nJnYe2T2TR9vxeP++hxcaWnQA1X4JWHJevFzkQ/274YSdwsX9XzoxWrXiTMPKMXtoDOXgm3CCBqo7MHJlckiLweEP1q57EQAPhBJLx08UFXqG1ZAv0ZiQgbzvmzCGYiR0X56pFGR9baAsA8l3/w0kyHOQJt4MxkIAA2T8aX3AA6EkUt70fbIs9xQMEyff7hFebBPx8WjQhkneMryHV+ScXTb+ZZFZhTbCB7uZyEMFXVFat46XvI2FZHXRxTA78LdTyMl531PKF3id13FUVrBLI/39TIGzrOMtNZ1H6p2Kci+fZS62zxMR468bFm6cb9MPZ8wbfs2+qfFHdtXBY1WQPlXw3oEumDOuRrarNienYoTeN+ianuXJjFAlG0RLzSCfsocIubxzFufke/I7GgYi4j/FeJMy18pLIrlISUdYwmmb2JP1NYgiDxeGbfx6I/a7tGYupl1w5quBJ/nBrbVvVcHGWw5DHGAARwyU4o38/6XvjxH/zDa2y7JEFBNy6rCz2BgYmbGYeMdsm5HFH/8YaIObcqKWE=
    # CFCI_IDAAS_SECRET
    - secure: PpwRFajY4iItm84C9WiyLXPJK/eUhzk8gfGJnzoK1NEtbEthHjoys+tGeZz3niJcc4NCqxUgGsSBWivlQ/ye7sPNznUFlqrCSpLp+1EC1gNSHYTm/w7TZJUXwWgrFwCVNK2TYzriPJ0UV/Uxh6dn9EGnS0YX+9s1hpxZl0l27LVKMtiRYR+Nfquh3VwMwuFk1Tq1Wu45TbcO72Te41ctdBGp0eN3Om7v+NJutdW0w4Q2w27+8zASWMAQXzqr3vD9xUbI3cb8t4sXLl8mjT0fYGgjpTvA03/p9lRv5HZhru/DIkD1Cq+qJlUfjn0PG86baKsO4EPB5T044a1NGQEKh6nDkUL+r4pJ94RBVkXnOk/UmmI5wK0WmLXBGQw+C+Sy/sgInkDLX2yEo8kS5JObggw1xTSVG9pDfZKaJdp9+MLsWEhaN5ywBNPMpREdznK0gmszrUQ2IzkcyT3MpzjgCFG4nRhilNkVlJv8kiZ9RDTrnEmon9zJISKSszrjt67kVUqbJPJ0tvIk5vRZAb321qiecCxveiLSwirmotYpKGFl3u13bY+p+zakIhbUmKhLIPl2wLdmv2+0tJ00nAMgYZ6HEcWIsgbMZaOKv4wKAfNHTN6oUYRbpPSq/D96yKFjZHnlUJxxRp+aWvI5B3oN8o+NUEEELG9ym40Lb61KOOs=

    # Staging Unsecure Vars
    ##
    - STAGE_APP_NAME=opwb-stage
    - STAGE_CF_SPACE=dev
    - STAGE_APP_MANIFEST_PATH=manifest-staging.yml
    - STAGE_NUMBER_INSTANCES=1
    - STAGE_CFCI_WEB_ROOT=/marketplace/operator/
    - STAGE_CF_NODE_ENV=staging
    - STAGE_CFCI_SOFTLAYER_CDN_URL=http://223ae.http.dal05.cdn.softlayer.net
    - STAGE_CFCI_IDAAS_CALLBACK=https://opwb-stage.w3ibm.mybluemix.net/marketplace/operator/auth/sso/oidc/return
    # Staging Secure Vars
    ##
    # STAGE_CFCI_SESS_SECRET
    - secure: INISNeHw83P+D9q+59zQcNnPlkYlHWWDLi0nS01f/NgFhbk9aTn8CJ5zo54HAiKKda581PonUj7ulcvwMme6dpzhl9Ixi7YJ8NCaa2uli2zuaitrbaEE2dR0u7Vle/Wib9E+BYc6NCZ6ZI2xC5eOcH3BhVNrraJ0NLkBy37Qtb85zlJEXPZz2Qy+c8LohnhmX+mIYyxAnVlN9GGLyQs7TfGF4T1nUoR0AoFRvUmEOWvrnYDkoxeW0HF6h+3o1h7y/MaFffUNCC3KA4dClbvI8mTunsRt7/iZr/EffT+g35jVYq8peuG72pnnrvYYtWmZ/3txUn7KR7r6wq/BwkND1XViH4uhZPJT5g22hohOhCnmvdXqrqWzlLhTas8YTJKhCEhWdAkcGHw83F2xhiNr1z78JaRXQrwm4T7JQhMbDoOeeT471olGHzDhXcp2OTlgG8stFogCX3FZHrPF6ixJIzXSC0rdFQZT0LY+iYjc7otmF36Cu0j8Ko7ru6BpAb8EFMk/bXuM4IXTlz0C7zjCr2BBs5InHYJbW2AqLaUisfiEJeWb5IKb4cB70QSp5BsN4aodx7cMyGvKUPh9AR9vgVwmodCoCciYFCSjXRgGZiwfhX0tW4ukR9rRcxSeoc6fDkQ1INukEEVT0+WqrXPtFb+sH1z4mBqaPA4LHSqwpts=
    # STAGE_CFCI_IDAAS_CLIENT
    - secure: B/znduEsSeEpfG0KJMXOJhxrUbIMXkd1etzTT7eePGpBKjB7uaIdBX/7o/ZtKlI4swEqePTUb25v1HLbSYzRqAapPTenjX5HpedMndfg3KWuczblFSH753ZCpWfhMar9gQuVjLBa9cT0SD4JNI8jGfs3PdtlpBpRVG64MO+l749hXdbKTt8HJgkUJ3+AVK1Vko8ceVvPS2IHmORmTEgD7/8OjcGT6IkMtAv9VPVr7pw0KGGgCUMwCPWVj1BsYCNo3zOmzucah/ugx2Rf/xPKbFl8TyMRe3SWakbPLRaJXwQyDb8ehv4hX7Ev4Jty8D/RZCTajJYUk7JrA0CNg0VlZrOVy+3e9lRTyLNNCaPtp/5bEKfyl+3t0mx5P31eETPsUfBDSZHWqVuV08t/LUHDGmTFrl7XxZfSfahgk3KwVYrl7Pz4+uvdkB2cgis5XZ7CRyyUcxxZdv4PPRm3Bsuybk9Mnuj+qVcFFos0TxlZ8iUM/iPaeg4WNXg6YG+OxY8IG4JCKAEhXlXM7PDmVhZ+GHhLRtABuMtzuN8mm8tV4WbiFEb09l9fhvOLS5Af7JAd5ZZBnYQdCng4izirn1oQDaMy2FstlBkZJjXVW8wNJrx2pot92VT+/4SnUj3zCCwOKg34y1b8hYg/vDVDxYq43/w4GCPYoCSAKHETKRrcgBo=
    # STAGE_CFCI_IDAAS_SECRET
    - secure: aIkdDdhBVyDaYRo9Rf3MNr3STUhdwNFHI1E++jpEkeNb9SHNHqc/4ebOa8yFZHuwdVr3icO0J4tfEWb0GfvXZ8ZtWbycHc464KkedIQx853IypxVVhU/Z+8QiDim1nIjmYV8i2fM2xCmFgy/FGhJcHfXkybcoE6Ohb85G/PogNBVX4Ian9MR7Sz9pq1CVbx5BTJp0vn22nkzYP+t+/irXo2QSlFCULF8rzCgstcQ5L5JiTy0wa/Ne2EAa2N5o0xQi9JCNQEpIV4C976vuFUY3MryQZswSMMibLAyxco4pP9np4uVHQhq8XBJQ7Pa3FQlAq/JTnJn56R4LzvSl+vgPlnhnWCHjRQTjEJN/8QJTrn9ojK1Elch1j/S0X1de1zzPBixCh2Qf22VpoOoZozLaESNGJQzIFQvCNd68SVLTSR5GBsbwvOaj9ebHz3OtsvJyYPsogjeSw9NePOBfglWoz2lQwRxLfO5BoZr+GyYVToGbwslQdJ+BE2SQHO7sdHa4FroXQSBYORZ8O9mWZgDCX15tyQND9Nc6tddwVY4RnfYQ66oQWuliPsX6sBdwXZoonhq+tyFMOUMprN25J5FzuKPSFjvPinm/54YUS6msr/4O2EgLbkPf9xQSqCG+GsO/elklYsefsd8q5rBN8aoRNwW4gAf04iKIrzA5VMZ+B8=
