language: node_js
group: bluezone
node_js:
- 6.3.1
sudo: required
before_script:
- npm install -g gulp --progress false --depth 0
- npm install -g istanbul --progress false --depth 0
before_install:
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo apt-get update -q
- sudo apt-get install g++-4.8 -y
- npm install -g npm@3.10.4 --progress false --depth 0
- openssl aes-256-cbc -K $encrypted_cb79c5695895_key -iv $encrypted_cb79c5695895_iv -in server/certs/w3ApiCrtKey.tar.enc -out server/certs/w3ApiCrtKey.tar -d
- tar xvf server/certs/w3ApiCrtKey.tar
install:
- npm install
script:
- gulp test
- gulp build
deploy:
  skip_cleanup: true
  provider: script
  script: "./bin/deploy.sh"
  on:
    branch: master
    node: 6.3.1
env:
  global:
  # Common Unsecure Variables ( Same in prod / stage )
  - CF_ID=pkadiya@us.ibm.com
  - CF_ORG=MarketplaceOnboarding
  - CF_ENV_PREFIX=CFCI_
  - CFCI_TEST=TRUE
  - MEMORY_SIZE=512M
  - CFCI_SEC_PATH=home/
  - APP_PATH=./dist
  - APP_MANIFEST_PATH=./dist
  - PROJ_PATH=./
  - CXX=g++-4.8
  - CFCI_SOFTLAYER_AUTH_URL=https://dal05.objectstorage.softlayer.net/auth/v1.0/
  - CFCI_CLOUDANT_USERNAME=opwb
  # Common Secure Variables ( Same in prod / stage )
  # CF_PWD
  - secure: pwj19kzNTr6hZUyblF/AbkH8AsAivdF9YT3Z0gGpPS8CiWR1EIROwU/PQyn7fWlctc/+EOxI10pIF0l+ytBU5cGb8LtJqkMgyHgCTOUtxKkyzD0s3gGLIVlCX11EqbaaiXeZpGmQFS9N07GcsHqSFeD40Dq6RGcK6h7AZUTowT9NPnUi6Tghw0MmIFK0s+/FFBR72Kg/ugj1KD6npx2cLiaGjwd91m52HCz9Zsa8U9StsOj9s4F3NbLkqmdZTKa+FIol6lmCiHF2nKClWM0WZO3GSPQWvrcm1p+EYLkiy1/cz4d2xv90tPzUPcUz3OBS+XpV07t2JS0vWybS9ZeCLHFCBYzUlBJDjNRWL99BoxXfQ78uXhyuwOckhOPhVmL9ryOY4ZJcbfvXh+O4v0hYpnmNhby98bF5dUhZpevg9ZnaAe93w6HGwTXC4ojsee1a+OaiNvjwOEUy3Y59nQjVP0yKX7KgRLsmK0oSYOVA6D2diXRb0eqk3pGPl7xuvQm8OK/T5exbVRCFjb1ULBE++UQLtCHqiLJ4zrMBZ9AG6QPG2Yq7a8GCKP7RdOU/KUtM7+4nSI0vwdOUEChxAQupP2hvMIntBXOhogbfSu/QtO/yiqGg3MPClj9Lkk2BKMtlh2664EUs36pZbtRgdnzylGXDpVg35E9XwoTTWdQ2Y9U=
  # CFCI_REDIS_PASSWORD
  - secure: SC3EDyhn+xYtCOI8PKiuvJWIZUgY+yeknFlCT6qCG8+5pCJgrWZ0C33Giw12wNKeTKxDhPzJQvjYUgJxwlQMvwELucWi++5L17W2FzA7ZNM+VW2bFaV+oVS4LgGvJsZni8WUw6fa9KTzucBQ859PbD6LqEJ2U8DIvwh3Dwap87Zwbsr38hyVP+fqPNHkM+GWyp6b8+05Cd4WpmOadbzd4n4arGNVnTjFwwpkYWewHGdW1e48h5rwsyiaeGnGRiwB6+4cPSIQwvsez/2HQidYCreWdwjlke8n8Zmp+jK/4huzDUyyjzzW8Am6n5VmDbvlbzx6nmxkkDkPg66IrHAuIrjmErLE/dD1YKzyVksI6iGK/OQkBGwqh0S+ZmQLABLVtvT5KIGKr/BYVQ5eqKV+v0Gl344HE2qMkUs4qP/PLWDZVuO6Qr11D+dHoC7cybuUESMYKjPpnk38XMgTa4s3Ww4F/SVLo0b0fZ+5MGkhzk4qh880sc6rvA0iDlIQUxuuy7VPtUTOi6y9Q9SPKnDGzH67Ginpk+I1Om4tLwC41FKzZVk+Ey1+C5eXC8l7R0S/+PWF+4HKfT4gFSkLuau2JnRhj432Cy9JKz/ZsU3k2oKGu2YIcLi0r1RB8bS7JQxnPwkxWPvcIkJpv9bgY/5p7i1ep/t6dzwuFgp1pVcwDls=
  # CFCI_CLOUDANT_PASSWORD
  - secure: dU5G9H5P9NzjVKg4CB/+GZfNrqF7PJLI53HWr1uVKZJWV8sJfRQ0HDD/8IzuGPAUG6QTCAlCcFKoKVgco1JC8CbcILGEj9Gu98smu426nJO1Eu9TyiDFgeDAwuULlzauMOO8wXbEgEHEZ1SWQ1cd8OZ4d6u4yoqHdv8N/4bxoMk++q7MDoe2racIQKscumTRKkLop9Ub1bzwV4ADtqPHcD/1boPew+cJMLj4gJL0Ummcnrh3362b8pLlWHtEq1BGg6a/8uNwCoabYaZjQw6pBE1LdNbbN2hCP9YM77qumcN193Xgso2Wq+VJNkAWYQCBv7HLpDUU89C+2wYIddadknoFBYGjclkxA/c4gJibrf99HsFmM4si2kljgMjBvl8/lrkKz4BrhamxgEDmlJkijeWNjCspGG5q+XAe4lczsg5II8dQB7gwbKV0OTUS8P4YVacY4KAXxlFZVZ09ADiFbTz++rbn9HIVZc/B5TipN45cMHPeWKsuoMsNP83iOH8I89h/OykaBSUqyOT4xuVSHV9pbhL1GWgW4ugdsp8PvxvCGgfU5h1H/AqHRNDn/wuIc8cDOUaJ1OgBB44DAixeCNUS/u0TJTbLYh4O8D8g5eDZfgsE891HCMINoS6rQHDjgKL2IrqmprZUGC0y6mNKWZh5usrpIohKNbQkgEXFAZM=
  # Production Unsecure Vars
  ##
  - APP_NAME=opwb
  - CF_SPACE=prod
  - APP_MANIFEST_PATH=manifest-prod.yml
  - NUMBER_INSTANCES=1
  - CFCI_WEB_ROOT=/marketplace/operator/
  - CF_NODE_ENV=production
  - CFCI_SOFTLAYER_CDN_URL=http://29DB6.http.dal05.cdn.softlayer.net
  - CFCI_IDAAS_CALLBACK=https://opwb.w3ibm.mybluemix.net/marketplace/operator/auth/sso/oidc/return
  # Production Secure Vars
  ##
  # CFCI_SESS_SECRET
    - secure: SySTZoWn1cZcJEha0U8PCYDIWpuvTiJnTOWc2kGfF6lNFXxBzJI/RXofior+0pNXukZKbBit2WRdsyr5nhFeg42i2lJQ8Gs8pf+1B0ffCow8u48A6txP/COJuo/rA2zcHoobjg0mHlmgkZKv4yEFrV/4UVXexwT1oUAf6VrFIK/EiuOOj/T6McHS94a8p2Ks/Yw/pjiR8S5qKDVdZWxVDfbAJPx5o3Zn3y1CnqoUnTvl/L7kSpjhA2C+eA1QzQOKokjP6ywQkyXmZSj0VIdSFXTaJKpD9dxmr2SAOSiMq/t0pTrQ/edT9Q7oWWdy9QYdDQxVHmYDHgYaj49+p8yy7o0wqLfrFom0Ar84024MGhXJSKZJd2L+VTfexaYl1OSFBsWnvV22cG5v6fzhyDd/8Sm/URK2zC51Tf4zKg9HElayQolfIPGCHE0oR7DjRJq2lLyhaVPjuNOFwlKVSVO0uKXZHjde/Azoo62+1B89RLrKRVUwtL7fTq/MKH7NYYwDUgbuQhw0NBQT4pEwAiFZOucl4X533Qy13NxodK+f9GIPl/+iBFVw11BnNFggJGN3qXhottwtXIrR24qBGvo6zTJ+N0OmJytaMBmfcYwx40XJe8rtqrRuLSGpDHrh2dXl8A9YmfzDnrprZnS74yJjvvki47R9/6grpb9n61Bw0qg=
  # CFCI_IDAAS_CLIENT
    - secure: A4AAvaKzfMc6Afoks/pKEfTYvUfJyYdupwSMHJJPaz8KflWkkpo/65LZAJGVsdC4V3Un7vUpasGQI4wxka8sez4HpLxm7Ar/eFBZzyiF9e7ZPyzaNo/V/SFNOUXMdFhAu1uTf/fcCpw6aS/YTj+2ywlGS5GCF6wThAiMkmaxeBRy3JHNX84ttvVzeXptjTvRrbEkj4IUZd5ZjqqHpZn2KQWGdf1l4aZnodrE50Na2BjtAM+/N7fZHAs/j4rI8LV4isVXdPUOFR03XoiNm+lJppEf/soVoGZD+W51UOCnodHd0pvdKNFoVjUaFQfztdjwwZS++ksiXDXgApQ0waXirv7E/xJGcu9m3dmSDn5/gezH131/ueS/W1rInuMrJRglu9+O10JALKjueZYkqI4tOgRfawidLS41aiKcyWkIJmIP5TPxBdjOCWgp09tko7L7gACu/X6YGxfCfMi1Pzjiw8MItlPSgcpGRPGhG4TSuHhFnRjN76K7LIloMu3FpaCwKUTOenc1O3EvIMbiHzsurIJP2eEBi1dPuRY36ARpFTmVfb0o8w/wgqDsRtQn2o6898XSHf6SPNFVFuYWJoDgPFoMArQrCRj18hJcnub8zVfMFnhso6n7bAVy8K3nowSvMjT1r2lRoVlQkKBuNQY5OScMH4sUrHBX/3HtlvX1AWA=
  # CFCI_IDAAS_SECRET
    - secure: rgXLurHQxaB4drkcdvZDrPe+kFKdlULeBJD2h8BISJgXoGgXiTwSXuMeXU+XPxXlanYonmFX7OMdxEKTO6QwJBuWSm5pJ870Ev8FPxhFbHYuUyoXOkGXqBQzt+QjazhaIbhvNWCvnu5bln1pihZ8GIDmkY57BBW/rj7m77npjXkWC7bMGKF1Ilpanp2jbNZWN+LR+U6fBqhjun7QVPRuIeRA7gKFj50NZavoSlX8btSCAk080JneIaqPlGMS8npgcvKoxlG70Nj6hBVdMkM1FvDSutT4KkIveRuvjv1ieMoVjER4VO353TOM6jzx9rcDtGEUnGNwoLlLq8FM0hYQORWWYMcrCMxDe6kJJH+PcvXBaITfScM05x78fgTuNZmkn7aNrMlmU5u1ONLi/o6A5wBuCAMjuz92exzrmik7PNW1A9CAy3azTN9HG30punJuGmtlYCMeToeTFcQosX8EZijRuws08YIzBdCSYl1cRfpTov7xCj2KgAXzw+2+fh+zbMb1CVcTOx5GfRDn11r2081hEw5AJsAig/DEcvvw75/8iqj5L3HQQEWsk307M0/t0XOkTO0ayJUUYLb18KjUQ7TGs6U4wM9jrZZ0f3nNUzPpNe3wQNT115RzuIz20qYhqetYVVxSLdE1Q2Bctt08lDI/TACrSWMuGq+A3ckUwQg=

  # Staging Unsecure Vars
  ##
  - STAGE_APP_NAME=opwb-stage
  - STAGE_CF_SPACE=dev
  - STAGE_APP_MANIFEST_PATH=manifest-staging.yml
  - STAGE_NUMBER_INSTANCES=1
  - STAGE_CFCI_WEB_ROOT=/marketplace/operator/
  - STAGE_CF_NODE_ENV=staging
  - STAGE_CFCI_SOFTLAYER_CDN_URL=http://223ae.http.dal05.cdn.softlayer.net
  - STAGE_CFCI_IDAAS_CALLBACK=https://opwb-stage.w3ibm.mybluemix.net/marketplace/operator/auth/sso/oidc/return
  # Staging Secure Vars
  ##
  # STAGE_CFCI_SESS_SECRET
    - secure: JeV3rOtcjsT1CGYoQenkj1PNyrUz5F2rbkiQQLooJxlniAPN0w5yfgyoZ7fwoMSsT1F1ut2ckmi6qeE6HV98lK96mhW2QPZgzwqGSga8W/sSkT1Jvzd2Xrn9m4wTQdvNIkosn/N2+pmPI+SV/htDx5L4Mo0HXvcgyyJbP67lBW5/8Nn6DuQSN9f7jPqD3hP8vhj1nrr/Kt1Cj+S9TUJpr7jyyE6AP/x/wWCFBs6VWilQeEZnbv52sXJgNLwELXnzybQiG/FHXyat40t4iIAJMdIdF9opygPXETwAsw7gSFmGNH2ga16tk0U0D0ZhVvu9LrsG3ZhRLyfNAV9mY2RDyCvJ/PLKE1oGoYUXCZvstZOWTkxz9ZM2wM0O2KVKt/6tmJOAWRW6mGdBf7jGiqaApPxzf5jp8Yo19vHMaQvAvb0HgZoIDYBW0H2pPOCYjdbWcJu79QSrVE9NGCGSPaImsMLlZdxwA66maso8uA2ekUJGOux1vi8+JHtfMaXmlV8Rk8buPGABiCbdWSPl1KscdSHUiObkD92X3+5hzojV2K/6X9F5GnRz0v0GjZ+vokItRLhU0ChXh6uo1tfZw0mPUUgjgA6zBYruLSBffwre9n4SiDImi6NHjpCLgbheZrF6FKhO+dacNgLEFygcu2gpBSY2bwOJdxBJU4RMSDyj/Y0=
  # STAGE_CFCI_IDAAS_CLIENT
    - secure: TA2sBhA/WFz65amkGs9crXb6jbIJmHCSnkfxGw/VRFmnsPiG5cUoOtbsn6dy0WnTijozJ3HE57EteUh8yAoZmgKTi7TyB3hRRVI8CTkHjTFrgtOG1jXR8QuEDYfXj9J0NCEmcj6ikhCsSsVpJgzk1HDxrd+4FIj7Zs3/JviBGrwEbS5SL16O70vEETyB4HtUZUPewwq+wCgRfYThyXMe9v+b5JpHAHdYwz7Qx8Ac/4de5ZPJNgQ2Bj1lSyOOic2Va43Pus0OZT3XZJE+zzf4stzqcJEbvU9otKFrci9sIoGudTiXYyXI+HEVQLzgFUKscP1dtj98GvhogF7mgm9qKsc/ew5hyRZINK+6qS/TAKOdJ1QhLOIMNGnteU42F2mI+LP4Eo3MgzBPHc1rjE5Xi+qurycMLrY8Eg7L3GvQdKCf9VVC+bUwDGRw83g1B51gyoJCNrUrgaHJpDN27Es5hIK68ZaXo/ePtZ9X70h5NihvyLr6JLOIU2If1Sk5fH2F2ibHnKkzOex0j1CmxzGPJrNcZseD0RJjvB/c3qJTP6IgdROmxNhHJgWkNj1FAyjiHF/q0mosPa3E5R0bhHLiK1Kn3clswK8HmkvdeLIsCe8FQIU+7oDFwg4I+MoaujzLL+W9iAfQMtinapxlehVkrGOcnh9ofNg1ffx9tGpy8dg=
  # STAGE_CFCI_IDAAS_SECRET
    - secure: CiVQVirOEDQ3O4VPwbMj/ppOumBCU3LC3LbTmextNgH6Xv8Osob7y32IVVGEwlmxHqn9WAdccgH2EphFfpgbiIOD/gV0q0fwTvFbwIlPk8oVdQmZt3KqqaSBLI101a/SDMzqX3zmisBEqswcHke3oPfBigIxOWB0hVW8Qe8t/4O2XMfhs/JEU492lXWK3346wFBxxpM6IAt7xmzjrZuco+k3AfQZTIdVLgfNRyRMyXwodyd9LaeOlUud52FXxdjV68q7Qj8i7WDpc1CYv7kE5v/PvENBANJPgQ5oFZTt74l7Gfx3nnjjFhN8CzFdZfXSBl666ARoDmg0TeCr6PSU2bttNHE1pRoG0VE3yo6cg5H9PfOMVTw0lxPiO11Bb7NqLpRZKixNM7UzJ5wWncvdhDUG/vkOh3rFw5CeF5KDPxf4IUjFQkP3o76AUgOiPoiIT7Xks0odqa1EQDmbD84TU+FsZp/oTerb8pd5CUkOMc8krSUqlYtYuwvo8T101OGvFdNrEtYpY1h4sqjSIMxOYHbxpJlV97VJXI6xF5RSl3IvCkOCsFEpXnFkNq4kqOg+dvZ9M2Q8ooeyDXWJnF0WiLc75KqdX9M0JvWTCoBYET3DDfw51stepY06PuJMBDXrWdBA96bWKCUQdLx4fbP3rMYQyh2IddY7OqtFxCMeu6A=