//Licensed Materials - Property of IBM
//
//@ Copyright IBM Corp. 2015 All Rights Reserved
//
//US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP
//Schedule Contract with IBM Corp.
var util = require('util');

/**
 * `InternalOAuthError` error.
 *
 * InternalOAuthError wraps errors generated by node-oauth.  By wrapping these
 * objects, error messages can be formatted in a manner that aids in debugging
 * OAuth issues.
 *
 * @api public
 */
function InternalOAuthError(message, err, context) {
  Error.call(this);
  Error.captureStackTrace(this, context);
  this.name = 'InternalOAuthError';
  this.message = message;
  this.oauthError = err;
}

/**
 * Inherit from `Error`.
 */
util.inherits(InternalOAuthError, Error);

/**
 * Returns a string representing the error.
 *
 * @return {String}
 * @api public
 */
InternalOAuthError.prototype.toString = function prototypeToString() {
  var m = this.message;
  if (this.oauthError) {
    if (this.oauthError instanceof Error) {
      m += ' (' + this.oauthError + ')';
    }
    else if (this.oauthError.statusCode && this.oauthError.data) {
      m += ' (status: ' + this.oauthError.statusCode + ' data: ' + this.oauthError.data + ')';
    }
  }
  return m;
};

/**
 * Expose `InternalOAuthError`.
 */
module.exports = InternalOAuthError;
